name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ci-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft != true
    strategy:
      matrix:
        "python-version": ["3.7", "3.11"]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: "Install Poetry"
      run: "pip install poetry"
    - name: "Setup Python"
      uses: actions/setup-python@v4
      with:
        python-version: "${{ matrix.python-version }}"
        cache: "poetry"
    - name: "Install poetry dependencies"
      run: "poetry install --no-interaction"
    - uses: pre-commit/action@v3.0.0
